/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdRouteImport } from './routes/$id'
import { Route as ApiStatsDotjsRouteImport } from './routes/api/stats[.]js'
import { Route as DeleteIndexRouteImport } from './routes/delete/index'
import { Route as ApiFileSplatRouteImport } from './routes/api/file/$'
import { Route as ApiFileKeyRouteImport } from './routes/api/file/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsDotjsRoute = ApiStatsDotjsRouteImport.update({
  id: '/api/stats.js',
  path: '/api/stats.js',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteIndexRoute = DeleteIndexRouteImport.update({
  id: '/delete/',
  path: '/delete/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileSplatRoute = ApiFileSplatRouteImport.update({
  id: '/api/file/$',
  path: '/api/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileKeyRoute = ApiFileKeyRouteImport.update({
  id: '/api/file/$key',
  path: '/api/file/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/stats.js': typeof ApiStatsDotjsRoute
  '/delete/': typeof DeleteIndexRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/stats.js': typeof ApiStatsDotjsRoute
  '/delete': typeof DeleteIndexRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/stats.js': typeof ApiStatsDotjsRoute
  '/delete/': typeof DeleteIndexRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/api/stats.js'
    | '/delete/'
    | '/api/file/$'
    | '/api/file/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/api/stats.js'
    | '/delete'
    | '/api/file/$'
    | '/api/file/$key'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/api/stats.js'
    | '/delete/'
    | '/api/file/$'
    | '/api/file/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ApiStatsDotjsRoute: typeof ApiStatsDotjsRoute
  DeleteIndexRoute: typeof DeleteIndexRoute
  ApiFileSplatRoute: typeof ApiFileSplatRoute
  ApiFileKeyRoute: typeof ApiFileKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats.js': {
      id: '/api/stats.js'
      path: '/api/stats.js'
      fullPath: '/api/stats.js'
      preLoaderRoute: typeof ApiStatsDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete/': {
      id: '/delete/'
      path: '/delete'
      fullPath: '/delete/'
      preLoaderRoute: typeof DeleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$': {
      id: '/api/file/$'
      path: '/api/file/$'
      fullPath: '/api/file/$'
      preLoaderRoute: typeof ApiFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$key': {
      id: '/api/file/$key'
      path: '/api/file/$key'
      fullPath: '/api/file/$key'
      preLoaderRoute: typeof ApiFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ApiStatsDotjsRoute: ApiStatsDotjsRoute,
  DeleteIndexRoute: DeleteIndexRoute,
  ApiFileSplatRoute: ApiFileSplatRoute,
  ApiFileKeyRoute: ApiFileKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
